/*
 * The MIT License
 *
 * Copyright 2023 Felipe dos Santos.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package view;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import DAO.ConexaoBD;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Felipe
 */
public class viewPrincipal extends javax.swing.JFrame {

    Connection conn = null;

    /**
     * Creates new form viewPrincipal
     */
    public viewPrincipal() {
        initComponents();
        conn = ConexaoBD.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descktop = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        bttnSair = new javax.swing.JButton();
        bttnOs = new javax.swing.JButton();
        bttnCliente = new javax.swing.JButton();
        bttnSobre = new javax.swing.JButton();
        bttnUsuario = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        menCadastro = new javax.swing.JMenu();
        menCadastroCliente = new javax.swing.JMenuItem();
        menCadastroOs = new javax.swing.JMenuItem();
        menCadastroUsuario = new javax.swing.JMenuItem();
        menRelatorio = new javax.swing.JMenu();
        menRelatorioClientes = new javax.swing.JMenuItem();
        menRelatorioServicos = new javax.swing.JMenuItem();
        menAjuda = new javax.swing.JMenu();
        menAjudaSobre = new javax.swing.JMenuItem();
        menOpções = new javax.swing.JMenu();
        menOpcoesSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para controle de OS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        descktop.setBackground(new java.awt.Color(0, 153, 153));
        descktop.setPreferredSize(new java.awt.Dimension(670, 565));

        javax.swing.GroupLayout descktopLayout = new javax.swing.GroupLayout(descktop);
        descktop.setLayout(descktopLayout);
        descktopLayout.setHorizontalGroup(
            descktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        descktopLayout.setVerticalGroup(
            descktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuario.setText("Usuário");

        lblData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblData.setText("Data");

        bttnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-cancel-16.png"))); // NOI18N
        bttnSair.setText("Sair");
        bttnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSairActionPerformed(evt);
            }
        });

        bttnOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/os-48.png"))); // NOI18N
        bttnOs.setToolTipText("Ordem de Seviço");
        bttnOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnOsActionPerformed(evt);
            }
        });

        bttnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-people.gif"))); // NOI18N
        bttnCliente.setToolTipText("Cadastrar Clientes");
        bttnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnClienteActionPerformed(evt);
            }
        });

        bttnSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-about-48.png"))); // NOI18N
        bttnSobre.setToolTipText("Sobre");
        bttnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSobreActionPerformed(evt);
            }
        });

        bttnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-team-48.png"))); // NOI18N
        bttnUsuario.setToolTipText("Cadastrar Usuário");
        bttnUsuario.setEnabled(false);
        bttnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnUsuarioActionPerformed(evt);
            }
        });

        menCadastro.setText("Arquivo");

        menCadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menCadastroCliente.setText("Cliente");
        menCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastroClienteActionPerformed(evt);
            }
        });
        menCadastro.add(menCadastroCliente);

        menCadastroOs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menCadastroOs.setText("OS");
        menCadastroOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastroOsActionPerformed(evt);
            }
        });
        menCadastro.add(menCadastroOs);

        menCadastroUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menCadastroUsuario.setText("Usuário");
        menCadastroUsuario.setEnabled(false);
        menCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastroUsuarioActionPerformed(evt);
            }
        });
        menCadastro.add(menCadastroUsuario);

        menu.add(menCadastro);

        menRelatorio.setText("Relatório");
        menRelatorio.setEnabled(false);

        menRelatorioClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelatorioClientes.setText("Clientes");
        menRelatorioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelatorioClientesActionPerformed(evt);
            }
        });
        menRelatorio.add(menRelatorioClientes);

        menRelatorioServicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelatorioServicos.setText("Serviços");
        menRelatorioServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelatorioServicosActionPerformed(evt);
            }
        });
        menRelatorio.add(menRelatorioServicos);

        menu.add(menRelatorio);

        menAjuda.setText("Ajuda");

        menAjudaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menAjudaSobre.setText("Sobre");
        menAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAjudaSobreActionPerformed(evt);
            }
        });
        menAjuda.add(menAjudaSobre);

        menu.add(menAjuda);

        menOpções.setText("Opções");

        menOpcoesSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menOpcoesSair.setText("Sair");
        menOpcoesSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpcoesSairActionPerformed(evt);
            }
        });
        menOpções.add(menOpcoesSair);

        menu.add(menOpções);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(bttnOs, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(bttnSobre, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lblUsuario)
                            .addComponent(lblData)
                            .addComponent(bttnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bttnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(descktop, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descktop, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttnOs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttnSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnSair)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(866, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastroClienteActionPerformed
        // as linhas abaixo vão abrir através do botão cliente a viewCliente dentro do painel desktop pane.
        viewCliente cliente = new viewCliente();
        cliente.setVisible(true);
        descktop.add(cliente);

    }//GEN-LAST:event_menCadastroClienteActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //as linha abaixo substituiem  a label data pela data atual do sistema a inicializar o form
        Date data = new Date();
        DateFormat formatadorData = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatadorData.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void menOpcoesSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpcoesSairActionPerformed
        // exibe caixa de dialogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        } else {
        }
    }//GEN-LAST:event_menOpcoesSairActionPerformed

    private void bttnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSairActionPerformed
        // exibe caixa de dialogo no botão de sair
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        } else {
        }

    }//GEN-LAST:event_bttnSairActionPerformed

    private void menAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAjudaSobreActionPerformed
        // chamando a tela sobre pelo menu
        viewSobre sobre = new viewSobre();
        sobre.setVisible(true);

    }//GEN-LAST:event_menAjudaSobreActionPerformed

    private void menRelatorioServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelatorioServicosActionPerformed
        // gerando impressão do relatorio  de serviços
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão deste relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_NO_OPTION) {
            // imprimindo relatorio com o framework jasperReport
            try {
                // usando a classe JasperPrint para preparar a impressão de um relatorio
                JasperPrint print = JasperFillManager.fillReport("C:/reports/servicos.jasper", null, conn);
                // a linha abaixo exibi o relatorio atraves da classe JasperViewer
                JasperViewer.viewReport(print, false);
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "menRelatorioServico" + erro);
            }
        }
    }//GEN-LAST:event_menRelatorioServicosActionPerformed

    private void bttnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSobreActionPerformed
        // chamando a tela sobre pelo botao
        viewSobre sobre = new viewSobre();
        sobre.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bttnSobreActionPerformed

    private void menCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastroUsuarioActionPerformed
        // as linhas abaixo vão abrir do menu usuario a viewUsuarios dentro do painel desktop pane.
        viewUsuario usuario = new viewUsuario();
        usuario.setVisible(true);
        descktop.add(usuario);
    }//GEN-LAST:event_menCadastroUsuarioActionPerformed

    private void bttnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnClienteActionPerformed
        // as linhas abaixo vão abrir através do botão cliente a viewCliente dentro do painel desktop pane.
        viewCliente cliente = new viewCliente();
        cliente.setVisible(true);
        descktop.add(cliente);
    }//GEN-LAST:event_bttnClienteActionPerformed

    private void menCadastroOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastroOsActionPerformed
        // as linhas abaixo vão abrir através do menu cliente a viewCliente dentro do painel desktop pane.
        viewOS os = new viewOS();
        os.setVisible(true);
        descktop.add(os);
    }//GEN-LAST:event_menCadastroOsActionPerformed

    private void bttnOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnOsActionPerformed
        // as linhas abaixo vão abrir através do botão cliente a viewCliente dentro do painel desktop pane.
        viewOS os = new viewOS();
        os.setVisible(true);
        descktop.add(os);
    }//GEN-LAST:event_bttnOsActionPerformed

    private void menRelatorioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelatorioClientesActionPerformed
        // gerando impressão do relatorio  de clientes
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão deste relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_NO_OPTION) {
            // imprimindo relatorio com o framework jasperReport
            try {
                // usando a classe JasperPrint para preparar a impressão de um relatorio
                JasperPrint print = JasperFillManager.fillReport("C:/reports/clientes.jasper", null, conn);
                // a linha abaixo exibi o relatorio atraves da classe JasperViewer
                JasperViewer.viewReport(print, false);
            } catch (JRException erro) {
                JOptionPane.showMessageDialog(null, "menRelatorioClientes" + erro);
            }

        }
    }//GEN-LAST:event_menRelatorioClientesActionPerformed

    private void bttnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnUsuarioActionPerformed
        // as linhas abaixo vão abrir através do botão usuario a viewUsuarios dentro do painel desktop pane.
        viewUsuario usuario = new viewUsuario();
        usuario.setVisible(true);
        descktop.add(usuario);
    }//GEN-LAST:event_bttnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCliente;
    private javax.swing.JButton bttnOs;
    private javax.swing.JButton bttnSair;
    private javax.swing.JButton bttnSobre;
    public static javax.swing.JButton bttnUsuario;
    private javax.swing.JPanel descktop;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menAjuda;
    private javax.swing.JMenuItem menAjudaSobre;
    private javax.swing.JMenu menCadastro;
    private javax.swing.JMenuItem menCadastroCliente;
    private javax.swing.JMenuItem menCadastroOs;
    public static javax.swing.JMenuItem menCadastroUsuario;
    private javax.swing.JMenuItem menOpcoesSair;
    private javax.swing.JMenu menOpções;
    public static javax.swing.JMenu menRelatorio;
    private javax.swing.JMenuItem menRelatorioClientes;
    private javax.swing.JMenuItem menRelatorioServicos;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables

}
